name: Ruff and Bandit Linting

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Укажите нужную версию Python

      - name: Install Ruff and Bandit
        run: pip install ruff bandit

      - name: Run Ruff Format
        run: ruff format --line-length 120 .

      - name: Run Ruff Check with Fix
        run: ruff check --fix --select E,F,W,I,C4,SIM,ARG,FLY,LOG,PERF,COM --line-length 120 .

      - name: Run Ruff Additional Checks
        run: ruff check --select ANN,B,A,RET,SLF,PTH,TD,ERA,PL,RSE --line-length 120 --output-format=github .

      - name: Run Bandit Security Check
        run: bandit -r . --format sarif --output bandit-report.sarif
        continue-on-error: true # Bandit не должен блокировать CI, если найдены проблемы

      - name: Upload Bandit SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-report.sarif
        if: always() # Загружаем отчет даже при ошибках
