name: Ruff and Bandit Linting

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff and Bandit
        run: pip install ruff bandit

      - name: Run Ruff Format
        run: ruff format --line-length 120 .

      - name: Run Ruff Check with Fix
        run: ruff check --fix --select E,F,W,I,C4,SIM,ARG,FLY,LOG,PERF,COM --line-length 120 .

      - name: Run Ruff Additional Checks
        run: ruff check --select ANN,B,A,RET,SLF,PTH,TD,ERA,PL,RSE --line-length 120 --output-format=github .

      - name: Check for Python files
        run: |
          find . -name "*.py" > python_files.txt
          if [ -s python_files.txt ]; then
            echo "Python files found:"
            cat python_files.txt
          else
            echo "No Python files found in the repository."
          fi

      - name: Create empty SARIF file first
        run: |
          echo '{"version": "2.1.0", "runs": [{"tool": {"driver": {"name": "bandit"}}, "results": []}]}' > bandit-report.sarif
          echo "Created empty SARIF file as backup"

      - name: Run Bandit Security Check
        run: |
          if [ -s python_files.txt ]; then
            echo "Running Bandit on Python files..."
            bandit -r . --format sarif --output bandit-report.sarif || {
              echo "Bandit found issues or failed, keeping backup SARIF report"
            }
          else
            echo "No Python files found, using empty SARIF report."
          fi

      - name: Verify SARIF file
        run: |
          ls -la bandit-report.sarif
          echo "SARIF content:"
          cat bandit-report.sarif

      - name: Upload Bandit SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-report.sarif
        env:
          CODEQL_ACTION_DISABLE_TELEMETRY: true
        if: always()
