name: Ruff and Bandit Linting

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff and Bandit
        run: pip install ruff bandit

      - name: Run Ruff Format
        run: ruff format --line-length 120 .

      - name: Run Ruff Check with Fix
        run: ruff check --fix --select F,W,I,C4,SIM,ARG,FLY,LOG,PERF,COM --line-length 120 .

      - name: Run Ruff Additional Checks
        run: ruff check --select E501,ANN,B,A,RET,SLF,PTH,TD,ERA,PL,RSE --line-length 120 --output-format=github .

      - name: Check for Python files
        run: |
          find . -name "*.py" > python_files.txt
          if [ -s python_files.txt ]; then
            echo "Python files found:"
            cat python_files.txt
          else
            echo "No Python files found in the repository."
          fi

      - name: Run Bandit Security Check
        run: |
          if [ -s python_files.txt ]; then
            echo "Running Bandit security analysis..."
            bandit -r . || echo "Bandit found security issues, but continuing."
          else
            echo "Skipping Bandit because no Python files were found."
          fi
        continue-on-error: true
