name: Ruff and Bandit Linting

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff and Bandit
        run: pip install ruff bandit

      - name: Run Ruff Format
        run: ruff format --line-length 120 .

      - name: Run Ruff Check with Fix
        run: ruff check --fix --select E,F,W,I,C4,SIM,ARG,FLY,LOG,PERF,COM --line-length 120 .

      - name: Run Ruff Additional Checks
        run: ruff check --select ANN,B,A,RET,SLF,PTH,TD,ERA,PL,RSE --line-length 120 --output-format=github .

      - name: Create SARIF file
        run: |
          echo '{"version": "2.1.0", "runs": [{"tool": {"driver": {"name": "bandit"}}, "results": []}]}' > bandit-report.sarif

      - name: Run Bandit
        run: |
          if find . -name "*.py" -type f | head -1 | grep -q .; then
            echo "Python files found, running Bandit..."
            bandit -r . --format sarif --output bandit-report.sarif || echo "Bandit failed, keeping empty SARIF"
          else
            echo "No Python files found."
          fi

      - name: Debug SARIF file
        run: |
          echo "Current directory contents:"
          ls -la
          echo "SARIF file info:"
          ls -la bandit-report.sarif
          echo "SARIF file size:"
          wc -c bandit-report.sarif

      - name: Upload Bandit SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-report.sarif
        if: always()
